---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: true

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - echo localhost > hostfile
  - ansible-playbook tests/test.yml --syntax-check
  - ansible-playbook tests/test.yml -vvv
  - >
    ansible-playbook tests/test.yml
    | grep -q 'changed=0.*failed=0'
    && (echo 'playbook test: pass' && exit 0)
    || (echo 'playbook test: fail' && exit 1)


notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
