---
# tasks file for ansible-perl
- name: install cpanminus module manager
  apt: name={{item}} state=present
  with_items:
    - cpanminus
  tags: [perl,cpan,install]

# TODO - move this out to separate file
#   "{{item}}"
#   with_lines: cat files/modules.txt
- name: install perl modules
  cpanm: name={{item}}
  with_items:
    - File::Slurp
    - File::Tee
    - IO::Tee
    - Log::Log4perl
    - Devel::Cover
  tags: [perl,cpan,install]